# Generated by Django 6.0.3 on 2026-03-20 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catequista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoCatequesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_grupo', models.CharField(max_length=20)),
                ('lugar', models.CharField(max_length=150)),
                ('dia', models.CharField(max_length=50)),
                ('catequista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='catequesis.catequista')),
            ],
        ),
    ]
