# Generated by Django 6.0.3 on 2026-03-20 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catequesis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioCatequesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='catequesis.grupocatequesis')),
            ],
        ),
    ]
