# Generated by Django 6.0.3 on 2026-03-26 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catequesis', '0002_horariocatequesis'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatoTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('clave', models.CharField(max_length=30, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de formato',
                'verbose_name_plural': 'Tipos de formato',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='catequista',
            options={'ordering': ['nombre'], 'verbose_name': 'Catequista', 'verbose_name_plural': 'Catequistas'},
        ),
        migrations.AlterModelOptions(
            name='grupocatequesis',
            options={'ordering': ['numero_grupo'], 'verbose_name': 'Grupo de catequesis', 'verbose_name_plural': 'Grupos de catequesis'},
        ),
        migrations.AlterModelOptions(
            name='horariocatequesis',
            options={'ordering': ['grupo__numero_grupo', 'hora_inicio'], 'verbose_name': 'Horario de catequesis', 'verbose_name_plural': 'Horarios de catequesis'},
        ),
        migrations.CreateModel(
            name='FormatoCatequesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo', models.CharField(max_length=20)),
                ('titulo', models.CharField(max_length=255)),
                ('subtitulo', models.CharField(blank=True, max_length=255)),
                ('texto_pie', models.TextField(blank=True)),
                ('orientacion', models.CharField(choices=[('vertical', 'Vertical'), ('horizontal', 'Horizontal')], default='vertical', max_length=20)),
                ('activo', models.BooleanField(default=False)),
                ('usa_celdas', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formatos', to='catequesis.formatotipo')),
            ],
            options={
                'verbose_name': 'Formato de catequesis',
                'verbose_name_plural': 'Formatos de catequesis',
                'ordering': ['tipo__nombre', '-ciclo', '-fecha_creacion'],
                'unique_together': {('tipo', 'ciclo', 'titulo')},
            },
        ),
        migrations.CreateModel(
            name='FormatoCelda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.PositiveIntegerField()),
                ('columna', models.PositiveIntegerField()),
                ('contenido', models.CharField(blank=True, max_length=255)),
                ('destacado', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('formato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='celdas', to='catequesis.formatocatequesis')),
            ],
            options={
                'verbose_name': 'Celda del formato',
                'verbose_name_plural': 'Celdas del formato',
                'ordering': ['fila', 'columna', 'orden'],
                'unique_together': {('formato', 'fila', 'columna')},
            },
        ),
    ]
