# Generated by Django 6.0.3 on 2026-03-25 19:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('prefijo', models.CharField(max_length=10, unique=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Área de inventario',
                'verbose_name_plural': 'Áreas de inventario',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EstadoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Estado del inventario',
                'verbose_name_plural': 'Estados del inventario',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='BienInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=30, unique=True)),
                ('prefijo_area', models.CharField(blank=True, max_length=10)),
                ('descripcion', models.TextField()),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('observaciones', models.TextField(blank=True)),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='inventario/')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_alta', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bienes', to='inventario.areainventario')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bienes', to='inventario.estadoinventario')),
            ],
            options={
                'verbose_name': 'Bien de inventario',
                'verbose_name_plural': 'Bienes de inventario',
                'ordering': ['-fecha_alta', 'codigo'],
            },
        ),
    ]
