# Generated by Django 6.0.3 on 2026-03-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('comunion', 'Primera Comunión'), ('confirmacion', 'Confirmación')], max_length=20)),
                ('fecha', models.DateField()),
                ('nombre_completo', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('nombre_padre', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_madre', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_novio', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_padrino', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_madrina', models.CharField(blank=True, max_length=255, null=True)),
                ('lugar_clases', models.CharField(blank=True, max_length=150, null=True)),
                ('dia_clases', models.CharField(blank=True, max_length=50, null=True)),
                ('hora_clases', models.CharField(blank=True, max_length=50, null=True)),
                ('bautizo', models.BooleanField(default=False)),
                ('eucaristia', models.BooleanField(default=False)),
                ('confirmacion', models.BooleanField(default=False)),
                ('matrimonio', models.BooleanField(default=False)),
                ('acta_nacimiento', models.BooleanField(default=False)),
                ('boleta_bautizo', models.BooleanField(default=False)),
                ('boleta_confirmacion', models.BooleanField(default=False)),
                ('ine', models.BooleanField(default=False)),
                ('otros_documentos', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
