# Generated by Django 6.0.3 on 2026-03-20 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catequesis', '0002_horariocatequesis'),
        ('sacramentos', '0002_alter_inscripcion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='catequista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catequesis.catequista'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='grupo_catequesis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catequesis.grupocatequesis'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='horario_catequesis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catequesis.horariocatequesis'),
        ),
    ]
